version: '3.1'

services:
  # Webサーバー (Apache + PHP 5.6)
  web:
    # PHP 5.6 と Apache がセットになった公式イメージを使う
    image: php:5.6-apache
    volumes:
      # 今いるフォルダ（プロジェクト全体）をコンテナ内の /var/www/html に同期させる
      - .:/var/www/html
    ports:
      # PCの8000番ポートをコンテナの80番ポートに繋ぐ
      - "8000:80"
    # Apacheのmod_rewriteを有効にする（.htaccessのために必須）
    command: >
      sh -c "a2enmod rewrite && apache2-foreground"

  # データベース (MySQL 5.7)
  db:
    # さくらサーバーで問題になった文字コード問題を避けるため、MySQL 5.7 を使う
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: blog_local
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      # データをPC側に保存して、コンテナを消してもデータが消えないようにする
      - db-data:/var/lib/mysql

  # データベース管理ツール (phpMyAdmin)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      # PCの8080番ポートをphpMyAdminに繋ぐ
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306

volumes:
  db-data: