services:
  # Webサーバー (Apache + PHP 5.6)
  web:
    platform: linux/amd64
    image: php:5.6-apache
    volumes:
      - .:/var/www/html
    ports:
      - "8000:80"
    # ↓ ★このcommand行を修正しました！
    command: >
      sh -c "a2enmod rewrite && docker-php-ext-install pdo pdo_mysql mysql && apache2-foreground"

  # データベース (MySQL 5.7)
  db:
    platform: linux/amd64
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: blog_local
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db-data:/var/lib/mysql

  # データベース管理ツール (phpMyAdmin)
  phpmyadmin:
    platform: linux/amd64
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306

volumes:
  db-data: